### PR TITLE
Revamp the project structure and codebase

### PR DESCRIPTION
**Pull request by HSGamer**
This is to make this library compilable without building any NMS jars (Currently it's too much work to do just to add a new version)

This includes:
- Use NMS jars from [CodeMC](https://ci.codemc.io/) (I don't know about your repositories. It looks like a private one, and it's annoying to me)
- Drop versions prior to 1.7.X
- Make it both a library that can be shaded and a plugin that can be depended on
- Use standard Maven plugins so that we can build this on any OS
- And... Add 1_20_R3 (1.20.3, 1.20.4)

### CODE REVIEW

**Comment by masecla22** [comment]
Heyyo!

Thanks for the pull request!

Just a couple things I want to add on:

Is there a reason for dropping versions prior to 1.7? I understand the reasoning, in that noone uses them, but the whole point of the library was to ensure that this will work anywhere, to the point where there is a TODO item which specifically mentions "emulate villagers on versions prior to 1.3" 

Secondly, thanks a lot for implementing the versioning across modules! I tried doing it myself, but I recall having some issues with it, which is why I switched to this. 

The private repository for NMS jars is intentional, as distributing NMS jars is against the EULA, which makes public repositories likely to stop working, which is why I placed it behind a private repo.

Finally, I don't think shading is a good idea for NMS-interfacing plugin, as you reintroduce the requirement of developers having to go out and update their plugins, as opposed to people simply updating the VillagerGuiAPI plugin. 

Overall solid changes, and I'd love to implement most of them in the library!

**Comment by HSGamer** [comment]
> Finally, I don't think shading is a good idea for NMS-interfacing plugin, as you reintroduce the requirement of developers having to go out and update their plugins, as opposed to people simply updating the VillagerGuiAPI plugin.

That's their choice. There are edge cases where people want to shade the library instead of depending on the plugin.
But depending on the plugin is still a preferred way.

**Comment by HSGamer** [comment]
> Is there a reason for dropping versions prior to 1.7? I understand the reasoning, in that noone uses them, but the whole point of the library was to ensure that this will work anywhere, to the point where there is a TODO item which specifically mentions "emulate villagers on versions prior to 1.3"

For most parts, I can't make the NMS jars for these versions.
But I think it's too much for a library targeting Spigot servers.

**Comment by HSGamer** [comment]
> The private repository for NMS jars is intentional, as distributing NMS jars is against the EULA, which makes public repositories likely to stop working, which is why I placed it behind a private repo.

That's up for discussion. But it's fine to just depend on it while developing (???). We don't distribute these jars anyways.
https://github.com/GamerCoder215/MobChip/
https://github.com/Updated-NoCheatPlus/NoCheatPlus

**Comment by masecla22** [comment]
This was fully merged!

**Pull request closed without merging**
